/**
 * Minimal .env file loader for ~/.longeragent/.env.
 *
 * Loads KEY=VALUE pairs into process.env with override semantics —
 * values in .env take precedence over existing environment variables.
 * This ensures keys pasted during `longeragent init` always win.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { getLongerAgentHomeDir } from "./home-path.js";

const ENV_FILE = ".env";

function envFilePath(homeDir?: string): string {
  return join(homeDir ?? getLongerAgentHomeDir(), ENV_FILE);
}

/**
 * Load ~/.longeragent/.env into process.env (override mode).
 * Silently skips if file doesn't exist or is unreadable.
 */
export function loadDotenv(homeDir?: string): void {
  const path = envFilePath(homeDir);
  if (!existsSync(path)) return;

  let content: string;
  try {
    content = readFileSync(path, "utf-8");
  } catch {
    return;
  }

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx <= 0) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();
    // Strip surrounding quotes
    if ((value.startsWith('"') && value.endsWith('"'))
      || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    process.env[key] = value;
  }
}

/**
 * Write or update a key in ~/.longeragent/.env.
 * Preserves existing entries; updates value if key already exists.
 */
export function setDotenvKey(key: string, value: string, homeDir?: string): void {
  const dir = homeDir ?? getLongerAgentHomeDir();
  mkdirSync(dir, { recursive: true });
  const path = envFilePath(dir);

  let lines: string[] = [];
  if (existsSync(path)) {
    try {
      lines = readFileSync(path, "utf-8").split("\n");
    } catch {
      lines = [];
    }
  }

  // Check if key already exists — update in place
  let found = false;
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim();
    if (trimmed.startsWith(`${key}=`)) {
      lines[i] = `${key}=${value}`;
      found = true;
      break;
    }
  }

  if (!found) {
    // Add header comment if file is empty
    if (lines.length === 0 || (lines.length === 1 && lines[0].trim() === "")) {
      lines = [
        "# LongerAgent API keys",
        `# Generated by 'longeragent init'`,
        "",
      ];
    }
    lines.push(`${key}=${value}`);
  }

  // Ensure trailing newline
  const content = lines.join("\n").trimEnd() + "\n";
  writeFileSync(path, content, { mode: 0o600 });

  // Also set in current process so subsequent wizard steps can detect it
  process.env[key] = value;
}
